### ISSUE TITLE
V1.3 not working on windows 11

### ISSUE THREAD

**Issue by DRCRecoveryData** [rainxh11/WinSxS_Cleaner#2]
Hi,

The release win32 not working on windows 11 only build 1.0 working

**Comment by rainxh11** [comment]
added .NET Self-Contained Release, other release requires .NET 6 runtime installed.

**Comment by rainxh11** [comment]
https://github.com/rainxh11/WinSxS_Cleaner/releases/download/1.3/WinSxSCleaner-win32-1.3-nodotnet.zip
